#ifndef JRCONSTANTS_H
#define JRCONSTANTS_H
#include <wx/event.h>

  enum{
    PLAY_BUTTON,
    PAUSE_BUTTON,
    SKIP_BUTTON,
    STOP_BUTTON,
    CLEAR_BUTTON,
    HELP_BUTTON,
    STRIP_BUTTON,
    CONT_BUTTON,
    SESSION_BUTTON,
    NEW_BUTTON,
    DELETE_BUTTON,
    LOAD_BUTTON,
    REFRESH_BUTTON,
    LOAD_FILE_BUTTON,
    LOAD_DIR_BUTTON,
    REZOOM_BUTTON,
    RSTH_BUTTON,
    INCH_BUTTON,
    DECH_BUTTON,
    CACHE_BUTTON,
    PRGS_SLIDER,
    PAINT_PAINT,
    LIST_ITEM,
    MEDIA_CTRL,
    TIMER_ID,
    TXT_TIMER_ID,
    MEDIA_TIMER_ID,
    DELAY_DRAG_TIMER_ID,
    CONTEXT_MENU_ID,
    RESET_ZOOM_MENU,
    RESET_HEIGHT_MENU,
    CHANGE_RES_MENU,
    SESSION_MANAGER,
    wxID_BUTTONPLAY,
    wxID_BUTTONSTOP,
    wxID_BUTTONNEXT,
    wxID_SLIDER,
    wxID_GAUGE,
    wxID_VOLSLIDER,
    META_PANEL
  };

  wxDECLARE_EVENT(SONG_ACTIVATED, wxCommandEvent);
  wxDECLARE_EVENT(TELL_SEEK, wxCommandEvent);
  wxDECLARE_EVENT(DECODE_ME_EVT, wxCommandEvent);
  wxDECLARE_EVENT(UPDATE_PATH_EVT, wxCommandEvent);
  wxDECLARE_EVENT(LIST_ITEM_IN_FOCUS_EVT, wxCommandEvent);
#endif
